platform :ios, '7.0'
link_with ‘HelloWorld’
pod 'AFNetworking'
pod 'FMDB'
pod 'GoogleAnalytics-iOS-SDK'
pod 'ADClusterMapView'
pod 'MKMapView-ZoomLevel'
pod 'MBProgressHUD'
pod 'UIViewController+HUD'
pod 'FormatterKit'
pod 'CocoaLumberjack'
pod 'skpsmtpmessage'
pod 'MKNumberBadgeView'
pod 'RSDayFlow'
pod 'SHPieChartView'
#pod 'PaperFoldMenuController'
